### ISSUE TITLE
Track teacher location

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/flex-site#12]
A filterable/sortable list showing teachers and their event (or prep, collaboration, etc.)

Date filtered too.

**Comment by haggyshan** [comment]
Tylere, I think this needs to be a high priority for Jeremy and Joanna to make sure every teacher has signed up but also for the office to identify where the teacher is .  Not sure how to change it to high priority.

**Comment by tylerecouture** [comment]
I relabeled this one ti High, and added you as a collaborator so you can add/edit/label issues if you want to.

**Comment by haggyshan** [comment]
Okay thanks.  I tried to do some changes on my last login but it wouldn't let me.  I'll try on this one.
shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________
