### ISSUE TITLE
Print or export event list from admin site as a pdf OR excel

### ISSUE THREAD

**Issue by haggyshan** [timberline-secondary/flex-site#36]

**Comment by tylerecouture** [comment]
Does this have to be from the admin site? I can change/tweak some things about how it is displayed, but it's an automatic back end that is provided with the platform I'm using.  Custom stuff like this is much easier for me to add to the public site. I can limit what is available to who.  Currently 4 levels of permission: Public, Student, Staff, and Admin (as in you, me, etc with access to Admin site).

**Comment by haggyshan** [comment]
All can be from the public site.  Probably easier that way instead of adding people to the admin site.
Shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________

**Comment by tylerecouture** [comment]
A plugin to export data directly from the table:
http://jsfiddle.net/marcelk/6gd9w79u/
