### ISSUE TITLE
Student suggestion: more info on selected events

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/flex-site#49]
In the box at the top where ti shows what events students have chosen, they should be able to click or hover to get the full event info.

**Comment by kinglyduck** [comment]
![more info](https://cloud.githubusercontent.com/assets/12159072/21666468/ae45ea92-d2a6-11e6-95a7-b839217486d5.PNG)
is this okay?

**Comment by tylerecouture** [comment]
Can you add teachers,  location and location.name in brackets after location? Also for mobile I think it will work better as a bootstrap modal popup rather than a popover.
