### ISSUE TITLE
Eventually - add the "5 C's" to the Categories instead of the current selection

### ISSUE THREAD

**Issue by haggyshan** [timberline-secondary/flex-site#55]
Add core competencies as the category labels for semester 2

**Comment by tylerecouture** [comment]
Question: will they only be picking ONE of the C's or do you want them to be able to pick multiple C's? Makes a big difference to how I code it.

**Comment by tylerecouture** [comment]
This can be done from the admin menu.  Just delete the old ones and add the new ones when we want to change them: 

https://timberline2ary.ca/admin/events/category/
