### ISSUE TITLE
add a check box above attendance for all absent

### ISSUE THREAD

**Issue by haggyshan** [timberline-secondary/flex-site#62]
add a check box at the top of the absent column in the registration tables to apply to all for the key pad entry "initialization" so teachers won't have to individually check absent box beside ALL the students' names.

**Comment by tylerecouture** [comment]
Doesn't it do this automatically?  When you initialize the keypad it should mark all students absent, and new registrations should be absent by default.  If not this is a bug. (This is separate from the suggestion of adding a button, which is a good idea regardless)

**Comment by haggyshan** [comment]
I didn’t get that far.  Just saw that pop up message.
shan

**Comment by tylerecouture** [comment]
OK, good!
