### ISSUE TITLE
Reset student password if not student homeroom teacher

### ISSUE THREAD

**Issue by haggyshan** [timberline-secondary/flex-site#83]
Under the admin section, have a space where a student's password can be reset by someone other than just their homeroom teacher.

**Comment by tylerecouture** [comment]
Admins can do this:
Admin > Database Management > Users > Search for User and open the record by clicking their student number

Then at the top you will see, in small words:
`Raw passwords are not stored, so there is no way to see this user's password, but you can change the password using this form.`

Click the form to set a new password.

Reopen this issue if you want any teacher to be able to reset any password.
