### ISSUE TITLE
Button to unselect all in Attedance window

### ISSUE THREAD

**Issue by haggyshan** [timberline-secondary/flex-site#85]
Twice now, when I’ve gone to report my Flex attendance, all of the 42 students are checked off as absent. I have to undo it for every kid. Is there a way of fixing this?

**Comment by tylerecouture** [comment]
This is probably because you have the Keypad Entry option on. Keypad entry
requires student to be absent by default.  If these are new events, I
suspect you are copying an event that had keypad entry on?

I'll add a button to turn it off

**Comment by tylerecouture** [comment]
Cool, I can just reply to the email and it shows up in the GitHub issue. Never realized that before!

**Comment by haggyshan** [comment]
It was Terry and that's what I told her BUT it doesn't help when you have to go through and uncheck 40 people registered in your class.  I tried just turning it off BUT it doesn't uncheck the already checked students.  Can you include that action in there.
Thanks
shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________

**Comment by haggyshan** [comment]
Nice.  Just emailed you back back CC's your school email just in case.
shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________

**Comment by haggyshan** [comment]
Niiice
shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________
